# Generated by Django 5.2 on 2025-04-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(null=True)),
                ("completion_date", models.DateTimeField(null=True)),
                ("status", models.IntegerField()),
                ("process_status", models.IntegerField()),
                ("address", models.TextField()),
                ("coord_x", models.FloatField()),
                ("coord_y", models.FloatField()),
                ("kind_of_appeal_id", models.IntegerField()),
                ("category_id", models.IntegerField(null=True)),
                ("received_from", models.CharField(max_length=255, null=True)),
                ("appeal_type_en", models.CharField(max_length=255, null=True)),
                ("appeal_type_ru", models.CharField(max_length=255, null=True)),
                ("appeal_type_kk", models.CharField(max_length=255, null=True)),
                ("location", models.TextField(null=True)),
                ("hexagon_id", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
