# Generated by Django 5.2 on 2025-04-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="description",
            field=models.TextField(default="Без описания"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appeal",
            name="title",
            field=models.CharField(max_length=512),
        ),
    ]
