# Generated by Django 5.2 on 2025-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0002_alter_appeal_description_alter_appeal_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="address",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
