# Generated by Django 5.2 on 2025-04-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0004_alter_appeal_hexagon_id_alter_appeal_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Новое"), (2, "В работе"), (3, "Завершено")]
                    ),
                ),
                (
                    "process_status",
                    models.IntegerField(
                        choices=[
                            (1, "Принято"),
                            (2, "Обрабатывается"),
                            (3, "Отклонено"),
                        ]
                    ),
                ),
            ],
        ),
    ]
