# Generated by Django 5.2 on 2025-04-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0005_request"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Request",
        ),
        migrations.AlterField(
            model_name="appeal",
            name="process_status",
            field=models.IntegerField(
                choices=[(1, "Принято"), (2, "Обрабатывается"), (3, "Отклонено")]
            ),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Новое"), (2, "В работе"), (3, "Завершено")]
            ),
        ),
    ]
