# Generated by Django 5.2 on 2025-04-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0006_delete_request_alter_appeal_process_status_and_more"),
    ]

    operations = [
        migrations.RunSQL("SELECT 1")
    ]

