# Generated by Django 5.2 on 2025-04-03 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0008_appeal_boundary_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="district_boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="appeal",
            name="district_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
